export  const songsData = [
    {
        title: "All EYEZ ON ME",
        cover: "https://townsquare.media/site/812/files/2019/02/All-Eyez-on-Me-CROP.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
        artist: "TUPAC SHAKOR",
        link: "https://www.youtube.com/watch?v=H1HdZFgR-aA",
        year: 1996,
        id: Math.random(),
    },
    {
        title: "WITHOUT ME",
        cover: "https://i1.sndcdn.com/artworks-5euX0zBtxhbsKKMX-HaoHEQ-t500x500.jpg",
        artist: "EMINEM",
        link: "https://www.youtube.com/watch?v=YVkUvmDQ3HY&feature=youtu.be",
        year: 2002,
        id: Math.random(),
    },
    {
        title: "STILL DRE",
        cover: "https://ih1.redbubble.net/image.592334893.0096/fposter,small,wall_texture,product,750x1000.u1.jpg",
        artist: "Dr Dre feat. SNOOP DOG",
        link: "https://youtu.be/_CL6n0FJZpk",
        year: 1999,
        id: Math.random(),
    },
    {
        title: "SHOOK ONES",
        cover: "https://images.genius.com/0185f36774abc62781ae21e0328c4b75.480x480x1.jpg",
        artist: "MOBB DEPP",
        link: "https://www.youtube.com/watch?v=_CL6n0FJZpk&feature=youtu.be",
        year: 1995,
        id: Math.random(),
    },
    {
        title: "WELCOME TO JAMROCK",
        cover: "https://netstorage.metrolyrics.com/albums/6493714jpg.jpg",
        artist: "DAMIAN MARLEY",
        link: "https://www.youtube.com/watch?v=_GZlJGERbvE",
        year: 2005,
        id: Math.random(),
    },
    {
        title: "BIG POPPA",
        cover: "https://ae01.alicdn.com/kf/HTB1ouDSHMmTBuNjy1Xbq6yMrVXar/Custom-Canvas-Wall-Art-Christopher-Wallace-Poster-The-Notorious-B-I-G-Wallpaper-Rap-Music-Wall.jpg_q50.jpg",
        artist: "THE NOTORIOUS B.I.G.",
        link: "https://www.youtube.com/watch?v=phaJXp_zMYM",
        year: 1994,
        id: Math.random(),
    },
];