export  const songsData = [
    {
        title: "All EYEZ ON ME",
        cover: "https://townsquare.media/site/812/files/2019/02/All-Eyez-on-Me-CROP.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
        artist: "TUPAC SHAKOR",
        link: "https://www.youtube.com/watch?v=H1HdZFgR-aA",
        year: 1996,
        id: Math.random(),
        birth: "June 16, 1971",
        pic: "https://resizing.flixster.com/i9eOwDzhY-8Drshfd-LyAkPdlhY=/506x652/v2/https://flxt.tmsimg.com/v9/AllPhotos/63862/63862_v9_ba.jpg",
        Albums: "All eyez on me, The Don Killuminati,  Me Against the World",
    },
    {
        title: "WITHOUT ME",
        cover: "https://i1.sndcdn.com/artworks-5euX0zBtxhbsKKMX-HaoHEQ-t500x500.jpg",
        artist: "EMINEM",
        link: "https://www.youtube.com/watch?v=YVkUvmDQ3HY&feature=youtu.be",
        year: 2002,
        id: Math.random(),
        birth: "October 17, 1972",
        pic: "https://pyxis.nymag.com/v1/imgs/366/6c8/ebb38f865997f382aa27ae170f6b710852-eminem.rsquare.w1200.jpg",
        Albums: "Kamikaze, The Marshall Mathers LP, The Slim Shady LP",
    },
    {
        title: "STILL DRE",
        cover: "https://ih1.redbubble.net/image.592334893.0096/fposter,small,wall_texture,product,750x1000.u1.jpg",
        artist: "Dr Dre",
        link: "https://youtu.be/_CL6n0FJZpk",
        year: 1999,
        id: Math.random(),
        birth: " February 18, 1965",
        pic: "https://www.biography.com/.image/t_share/MTQ3NTI3MDgzNTIwNjk3ODM4/dr_dre_photo_by_christopher_pol_getty_images_entertainment_getty_120919208.jpg",
        Albums: "The Chronic, 2001, Compton",
    },
    {
        title: "SHOOK ONES",
        cover: "https://images.genius.com/0185f36774abc62781ae21e0328c4b75.480x480x1.jpg",
        artist: "MOBB DEPP",
        link: "https://www.youtube.com/watch?v=_CL6n0FJZpk&feature=youtu.be",
        year: 1995,
        id: Math.random(),
        birth: "1991",
        pic: "https://static.qobuz.com/images/artists/covers/medium/ed8c4b7b1ff1ed88935bbe86f7d0c8b4.jpg",
        Albums: "The Infamous , Hell on Earth, Murda Muzik",
    },
    {
        title: "WELCOME TO JAMROCK",
        cover: "https://netstorage.metrolyrics.com/albums/6493714jpg.jpg",
        artist: "DAMIAN MARLEY",
        link: "https://www.youtube.com/watch?v=_GZlJGERbvE",
        year: 2005,
        id: Math.random(),
        birth: "July 21, 1978",
        pic: "https://i.scdn.co/image/8c6081bd641058fada4bc68f35d37b8069cbb909",
        Albums: "Welcome to Jamrock, Stony Hill, Relatives",
    },
    {
        title: "BIG POPPA",
        cover: "https://ae01.alicdn.com/kf/HTB1ouDSHMmTBuNjy1Xbq6yMrVXar/Custom-Canvas-Wall-Art-Christopher-Wallace-Poster-The-Notorious-B-I-G-Wallpaper-Rap-Music-Wall.jpg_q50.jpg",
        artist: "THE NOTORIOUS B.I.G.",
        link: "https://www.youtube.com/watch?v=phaJXp_zMYM",
        year: 1994,
        id: Math.random(),
        birth: "May 21, 1972",
        pic: "https://static.highsnobiety.com/thumbor/zAvMmvksm4hlM4JuAeGJmXHPEqE=/1600x1067/static.highsnobiety.com/wp-content/uploads/2017/03/09140536/notorious-big-01.jpg",
        Albums: " Ready to Die , Life After Death, Born Again",
    },
];